import { NextRequest } from 'next/server';
import { z } from 'zod';
import { withAuth } from '@/middleware/auth';
import { linkTelegramAccount } from '@/services/telegram';
import { successResponse, errorResponse } from '@/utils/api-response';
import { logAudit } from '@/services/audit';
import { getClientIp } from '@/utils/request';
import { checkRateLimit, RATE_LIMITS } from '@/services/rate-limit';

const linkSchema = z.object({
  // Token is a short opaque code generated by the bot — anything past 100
  // chars is malformed. Hard cap stops a body-size DoS attempt.
  token: z.string().min(1).max(100),
});

export const POST = withAuth(async (request: NextRequest, { user }) => {
  try {
    // Sensitive bucket (3 per 15 min): without it, an attacker on a stolen
    // session could brute-force link tokens at line rate.
    const rl = await checkRateLimit(`user:${user.id}`, RATE_LIMITS.sensitive);
    if (!rl.allowed) {
      return errorResponse('Забагато спроб. Спробуйте через 15 хв.', 429);
    }

    const body = await request.json();
    const parsed = linkSchema.safeParse(body);
    if (!parsed.success) {
      return errorResponse('Токен не надано', 422);
    }

    const linked = await linkTelegramAccount(user.id, parsed.data.token);
    if (!linked) {
      // Audit failed link attempt — spikes are a useful signal for
      // "credentials stolen, attacker probing tokens".
      await logAudit({
        userId: user.id,
        actionType: 'user_edit',
        entityType: 'user',
        entityId: user.id,
        details: { action: 'telegram_link_attempt', success: false },
        ipAddress: getClientIp(request),
      });
      return errorResponse('Невалідний або прострочений токен', 400);
    }

    // Successful link is a security event — third-party identity now
    // attached to the account, can be used as a future login factor.
    await logAudit({
      userId: user.id,
      actionType: 'user_edit',
      entityType: 'user',
      entityId: user.id,
      details: { action: 'telegram_linked' },
      ipAddress: getClientIp(request),
    });

    return successResponse({ message: "Telegram акаунт прив'язано" });
  } catch {
    return errorResponse('Внутрішня помилка сервера', 500);
  }
});
